name: Release  

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Release 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install 
      - name: Perform build
        run: npm run build
      - name: Deploy page
        run: npm run deploy
      - name: Patch version
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          npm version patch -m "[skip actions] version %s"
          git push -o ci.skip origin
          git push -o ci.skip origin --tags
